# This workflow will run Test Case

name: Robot Framework CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
permissions:
  contents: read
 
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome]
     
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3
      
      - name: 🐍 Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12.4
   
      - name: 📦 Install dependencies
        run: |
          pip install -r requirements.txt
          pip list

      - name: 🌐 Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip curl gnupg
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" \
            > /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome --version
          chromedriver --version

      - name: 🔧 Install matching ChromeDriver
        run: |
            CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
            CHROME_MAJOR=$(echo $CHROME_VERSION | cut -d. -f1)
            DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR}")
            wget https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            sudo mv chromedriver /usr/local/bin/
            google-chrome --version
            chromedriver --version

      - name: 🐞 Debug Chrome
        run: |
          google-chrome --version
          chromedriver --version || true
   
      - name: 🧪🖥️ Test with RobotFramework
        run: |
          robot \
                --variable BROWSER:chrome \
                --variable HEADLESS:true \
                --outputdir results \
                .  
         
      - name: 📊 Test Report Generation
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: Report            # Name of the folder
          path: results/          # Path to test results