# This workflow will run Test Case

name: Robot Framework CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
permissions:
  contents: read
 
jobs:
  test:
    runs-on: ubuntu-latest
     
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3
      
      - name: 🐍 Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.12.4
   
      - name: 📦 Install dependencies
        run: |
          pip install -r requirements.txt

      - name: ⚙️ Install ChromeDriver
        run: |
          pip install webdriver-manager

      - name: 🐞 Debug Chrome
        run: |
          google-chrome --version
          chromedriver --version || true
   
      - name: 🧪 Test with RobotFramework
        run: |
          robot \
                --variable browser:chrome \
                --variable HEADLESS:True \
                --outputdir results \
                .  
         
      - name: 📊 Test Report Generation
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: Report                # Name of the folder
          path: report.html           # Path to test results